apiVersion: v1
version: 0.1.7
appVersion: "0.7"
description: A Helm chart for a highly available postfix relay in Kubernetes
name: postfix
keywords:
- postfix
sources:
- https://github.com/eldada/postfix-relay-kubernetes
maintainers:
- name: eldada
  email: eldada@jfrog.com
